### ISSUE TITLE
The x-axis labels are incorrect for the need-striage, needs-contact and site-wait graphs

### ISSUE THREAD

**Issue by past** [webcompat/webcompat-metrics-client#167]
Right now they alternate between 1 AM and 1 PM, when they should be more like the dates in needs-diagnosis.

**Comment by past** [comment]
What is weird is that the labels were correct yesterday, but they are back to incorrect today. The only reason I know that I'm not losing my mind is because I got some screenshots for a presentation!

**Comment by magsout** [comment]
the labels are incorrect https://webcompat-dashboard.herokuapp.com/needstriage?from=2019-03-28&to=2019-04-12

But with this range https://webcompat-dashboard.herokuapp.com/needstriage?from=2019-04-01&to=2019-04-12 they are correct.

**Comment by magsout** [comment]
I'm not sure to really understand the bug. I can forced the unit in day, but we loose hour by hour steps if we choose the same day for "from" and "to"

**Comment by magsout** [comment]
@past for example If I force `unit: day` https://webcompat-dashboard-pr-168.herokuapp.com/needstriage?from=2019-03-28&to=2019-04-12 the x labels are correct.

But for the same day the x labels are not correct https://webcompat-dashboard-pr-168.herokuapp.com/needstriage?from=2019-04-12&to=2019-04-12 


don't know if the hour unit is revelant or not.

**Comment by laghee** [comment]
@magsout It looks to me like this bug was originally obscured by not having enough data points (since we've only been collecting data from mid- or late March onward for triage, sitewait, and outreach). Fewer data points seems to make the x-axis... unhappy.

Right now when you look at the default graphs (as of today April 7 - May 7), the x-axis looks fine. But, mysteriously, if you **filter** for any period of time **shorter than 16 days** ... it goes back to the weird hour axis.

I'm not familiar enough with the details of chartjs to guess why 16 days would somehow be a significant unit of time 🤔... but maybe there's an issue in the filtering action somewhere? 🤷‍♀
