### ISSUE TITLE
Add Outreach Dashboard

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat-metrics-client#30]
It might be a good idea to have a outreach / needscontact dashboard. This bug is for documenting ideas around it.

**Comment by laghee** [comment]
👋  **Update:**  [Using notes](https://www.evernote.com/shard/s310/sh/47feabab-20b0-464c-97e1-0dd840f3a42b/789c36df533eb865) from @adamopenweb and @miketaylr, planning [threads](https://github.com/mozilla/webcompat-team-okrs/issues/2), and our discussion at AllHands, I'm mapping out the porting of the [prototype dashboard](http://adamstevenson.ca/mozilla/reports/outreach.html).

Given the amount of data to be fetched (and how much of some of the API payloads is unnecessary to our metrics), I think it would be better to store in Postgres and use queries to gather and manipulate data for the currently desired reports, rather than fetching from GitHub each time a page is loaded. Stored data could also be used for future dashboards/reports (new tables could be added, schemas could be adjusted, or everything could change -- who knows).

So far I've come up with 4 potential tables for a webcompat-metrics database:

<img width="592" alt="screenshot 2018-06-27 21 19 00" src="https://user-images.githubusercontent.com/20972610/41994764-d79b899a-7a4f-11e8-93cc-a433b77693b8.png">

A few [webhooks could be created](https://developer.github.com/v3/repos/hooks/#create-a-hook) and used to update the database when changes occur: 

`issues` and `issue_events` => [issues event](https://developer.github.com/v3/activity/events/types/#issuesevent)
`milestones` => [milestone event](https://developer.github.com/v3/activity/events/types/#milestoneevent)
`labels` => [label event](https://developer.github.com/v3/activity/events/types/#labelevent)

Since @karlcow will have the first unreachable shift, I'm planning to start with the server side. I'm hoping to figure out how to organize and serve the queries and the basic setup for Postgres over the next week or so.

Then I'll move on to trying not to make too big a mess in React with some help from @magsout 

And then, if all goes well ... something will be shipped. 🎉 

We'll see how things develop!

**Comment by karlcow** [comment]
Very cool @laghee 
Most of the server side development should go on 
https://github.com/webcompat/webcompat-metrics-server/

We would also need to figure out if we want to continue with heroku and so give you access to the deploy if yes. I will grant you access to the webcompat metrics server repo.

**Comment by karlcow** [comment]
@laghee 

> Given the amount of data to be fetched (and how much of some of the API payloads is unnecessary to our metrics), I think it would be better to store in Postgres

This will probably be useful for kickstarting your project 
https://github.com/josegonzalez/python-github-backup

**Comment by laghee** [comment]
@karlcow I assumed we were continuing with heroku, at least for now. If you can grant me access, that would be great for starting to set up postgres.

It looks like we'll need at least the [hobby-basic tier] (https://devcenter.heroku.com/articles/heroku-postgres-plans#plan-tiers)for the current number of issues, [which is $9/mo](https://elements.heroku.com/addons/heroku-postgresql#pricing) -- I think @miketaylr mentioned something about whether this could be covered by a budget request -- or maybe the Mozilla heroku account is already on a higher tier?

**Comment by miketaylr** [comment]
This should be on the Mozilla account, using a professional / standard dyno.

**Comment by karlcow** [comment]
1. Open an account on Heroku with your Mozilla address
2. Create a bug with the same parameters than https://bugzilla.mozilla.org/show_bug.cgi?id=1457375
    cc: @miketaylr on it. 
3. Once it is done I can grant you access to the webcompat-metrics-server project on heroku.

**Comment by laghee** [comment]
Bug 🐛 [created!] (https://bugzilla.mozilla.org/show_bug.cgi?id=1472085)

**Comment by laghee** [comment]
Since we have issues filed for each individual new dashboard, I don't think we need to keep this one that covers the first, generalized part of the project.
